CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    time_stamp TIMESTAMP,
    transaction_type VARCHAR(50) NOT NULL,
    account_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id)
);